name: "📚 Blog Updater"

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 0 * * *' # Runs Every Day

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "📥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "📚  Hashnode Updater"
        uses: "vineetsnegi/action-hashnode-blog@main"
        with:
          USERNAME: 'vineetsnegi' # Hashnode Username
          BLOG_URL: 'https://vineetsnegi.hashnode.dev/' # Blog URL
          STYLE: "blog-left"
          COUNT: 5 # MAX Visisble
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
